version: "3"
services:
  database:
    env_file:
      - ./.env
    image: postgres
    container_name: facefriend-db-test
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - facefriend_network
    volumes:
      - ./db/initial_setup.sql:/docker-entrypoint-initdb.d/initial_setup.sql
      - postgres_data:/var/lib/postgresql/data/


  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - database
      - redis
      - rabbitmq
    networks:
      - facefriend_network
    ports:
      - 8080:8080
    container_name: facefriend-app-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: facefriend_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    networks:
      - facefriend_network
    ports:
      - 6379:6379


  rabbitmq:
    image: rabbitmq:3.12.11-management
    container_name: facefriend_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
      - RABBITMQ_ERLANG_COOKIE = OJUZRGYJJNHYNJLZTPCM
    networks:
      - facefriend_network
    command: [
      "bash", "-c",
      "chmod 400 /var/lib/rabbitmq/.erlang.cookie; 
      rabbitmq-plugins enable rabbitmq_management;
      rabbitmq-plugins enable rabbitmq_stomp;
      rabbitmq-server" ]

volumes:
  postgres_data:

networks:
  facefriend_network:
    driver: bridge