spring:
  servlet:
    multipart:
      max-file-size: ENC(QEdqgrkc1SQ1MQiXhyAgxw==)
      max-request-size: ENC(LPYSKFia9XgqXJ3LGkU7Hw==)
  jpa:
    properties:
      hibernate:
        format_sql: ENC(/k2lAOOiToZinXyjPs043A==)
        dialect: ENC(hp39xonPsDFfQh0uP+QagZp+eTRY3ZAbQwHKlZn8sF4qdgSFLFfy/S3t7JZiU1qp)
    hibernate:
      ddl-auto: ENC(aYCGcw68x/rbuYvEdL4Lhg==)
    database: ENC(lqzJGxyaruG3vO12BiGSnjFhVXtQ/+Fo)
  datasource:
    url: ENC(wV42lv7kzXkiXlnYQ1a2bG1dONwCCIv2bBMaPQ4lhYAgukbfTQ7bTfWnPJTLkYQ2GabqhbvF04k=)
    driver-class-name: ENC(iqVYNwUdkSnuRBOTVhE4/vFEFLVHrzRqgat0OWx6wsA=)
    username: ENC(JMdQNyqE900MZFuuxX+EqHGrFzc8wbpG)
    password: ENC(boj14VTRgt8U1VxDmizlgW6H+4OgUKnm)
  data:
    redis:
      host: ENC(m/yqU98jpYwgO4T0cn+cbj84vU3Df5LB)
      port: ENC(Xmvsj7NQ241FjmCVl+CoJA==)
  cloud:
    aws:
      credentials:
        accessKey: ENC(AKIA4PECHEV4U7C4UN6X)
        secretKey: ENC(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)
      s3:
        bucket: ENC(SEJS5JtGMpaGfNbv0bo5/Z6lBlWUbjagZvXHZkCEVI8=)
        default-profile: ENC(86nUxZdzl1eLO73dgWZ/0nQ97ufNG4wHH+gAb7YXnsE/k8bx7w/Kxto9rJbgTkl/9sD39B/59r9pXlDyxh8/rxwIyWoY762DHdtI4vALuUMkoIOXy6bphDj7/7Zj+4mg)
        origin-postfix: ENC(p0xrguoxJfBD/ni12bsBCg==)
        generated-postfix: ENC(Puyqdr1silILjwFaVgy/6TWlyttYD85u)
        resume-postfix: ENC(Dg6Zti3FGjEBEHuX/YSqI0Cp6P/LFSLY)
      region:
        static: ENC(hcMa/BJepQBT0E9O7EiVpXd9V4raCcNe)
        auto: ENC(XRRrHE8GwP+ZEKyYkm+TBg==)
      stack:
        auto: ENC(7qYWPZ8gY4UWFUCFMe9IBQ==)
  mail:
    host: ENC(jZYnjrEyHZZ4o8h8LZidGkB2Xhgm/Vit)
    port: ENC(JuFjkiiT6DHuIaayqED9Ig==)
    username: ENC(FsUEuNq53OtzT7AVF6ljEkda1uM+UzU3DIoKwd8odsc=)
    password: ENC(9VcbNyNuTcOtbMjVV5chkLoAFVYy+BL+0x6OyJ6Rb9A=)
    properties:
      mail:
        smtp:
          auth: ENC(qP6dP401owtpbmLO9ZLsqQ==)
          starttls:
            enable: ENC(2/iPAAN2gOI7acxeL/Ae4w==)
            required: ENC(ylH6cx5TFINzE+Iaejk05g==)
          connectiontimeout: ENC(5VmkTIOsxDFGqFYJxpeRxQ==)
          timeout: ENC(1vRJaeCxUbBooMhkNGYAgA==)
          writetimeout: ENC(HgCUlmd2sIuCbfMtnMIDiw==)
    auth-code-expiration-millis: ENC(TiTMV9IAw23s+lb3rg5cEg==)


logging.level:
  org.hibernate.type: ENC(zpXUtRSonoW/8iNULYl71A==)


jwt:
  header: ENC(um8d5ji3oU1r1B+F1pK/hfIS3V0D9JmH)
  secret: ENC(KhoKRnYvfMbkW6KOxF2957PgwNBHw2xk4XvdogWgyp6gKr/nkQPNnWyQeOT41HBnDmwemvypAzA6Wa1Lf8he/8N89Tbogx3BbHafuAlY928=)


oauth2:
  provider:
    google:
      id: ENC(Rxxd9KP4koB4a3/M1NJVn0VgVkMounxvLanizrDFHPYC4fpBtXQICFnuNHUaKXPkZc2qiRelcHX9lfMucQi6Zv+J/azrksfjReRIPFIGBK42qyAqFHL0iA==)
      secret: ENC(yiPxkw/nRQr+aYBGy8/MO8wO/pEycXYqucC5cSPJ/qV7oaD1wJbYeqJfbB02CFXi)
      token-url: ENC(q8uAMwvhAPIGJCiXMXX1j9YSitxh5mIUFKUbvln8AFxanfCHUH3OI4/q35+oTxOr)
      info-url: ENC(i4B4j83Tp6Sg0bmIb5PXACW04oET9g0PMNZ0Gi2x7G4PQWpLcHWWFQn0h9j0sown0zSQhjs6KCg=)
      login-url: ENC(6cISkrFhAk1pqC2LNJwUfOjv83B85WVRnxH5cXRhsVGhNjpwB9aAmApxHNUE5r+YTZOqOYOnYSo=)
      scope: ENC(CCQMgZpF+j4QkzQtm/o8Xb+iSJ5E5YDx)
flask:
  generate-url: ENC(OzXrY2PX8uaoonLpKTWI8qnGJR3tFH7rfC5tspp6RYRNq/75DfOj++64bJta2Cf+2iC5wFzMJHo=)
  analyze-url: ENC(9D6R6D2eJFmhgwagCtzSRVmz+HLEq6VD8C1e3bBe92aTL05YhlZIAjLz4DB9JA09)